# Site settings
title: Ashley Champagne
github_username: ashleychampagne
description: >
  As the Director of Digital Scholarship, Ashley strategizes and coordinates the Library’s digital scholarship offerings with a talented team. Ashley is the PI of “New Frameworks to Preserve and Publish Born-Digital Art,” a project funded by the National Endowment for the Arts. She is co-Research Director on the “Stolen Relations: Recovering Stories of Indigenous Enslavement in the Americas” project, which is funded by the National Endowment for the Humanities. Ashley earned her Ph.D. in English from University of California, Santa Barbara in 2018.
 
url: "https://library.brown.edu/"

# Build settings
markdown: kramdown
theme: minima


