# Site settings
title: Ashley Champagne
github_username: ashleychampagne
description: >
Researcher, Teacher, Digital Humanist 
url: "https://library.brown.edu/"

# Build settings
markdown: kramdown
theme: minima


