# Site settings
title: An Example of a site
github_username: ashleychampagne
description: >
  This is a practice site to demo GitHub Pages.
 
url: "https://cdworkshops.github.io/cats"

# Build settings
markdown: kramdown
theme: minima


